### PR TITLE
Whisparr Addition Completes #111

### PR DESCRIPTION
**Pull request by pops64**
Works without errors. Ran test all day yesterday

### CODE REVIEW

**Comment by pops64** [comment]
I will try testing it. Unfortunately my indexers for torrents are currently broken

**Comment by pops64** [comment]
I tested it an it seems to do nothing. But I am unsure what you are trying to test for. Or the changes you made

**Comment by pops64** [comment]
Tested it. I had to force it with a capped bandwidth and up the time check interval. Because I couldn't find a slow torrent go figure. I had a torrent downloading and unmonitored it before I made theses changes. Upon rebuilding the container it did a check and saw my active torrent as unmonitored and removed the torrent.

**Comment by ManiMatter** [comment]
If you have a download in the queue that belongs to a movie/series that has been deleted in the meantime from whisparr it should be removed.

so add a new movie in whisparr, request a download for it, and then delete the movie. The script should then remove the download (orphan download)

**Comment by pops64** [comment]
I think we posted at the same time :P the unmonitored job worked just fine.
```
[INFO]: LOG_LEVEL = INFO: Only logging changes (switch to VERBOSE for more info)
[INFO]: >>> Removing unmonitored download: *******
```

**Comment by ManiMatter** [comment]
Try the orphan one pls

**Comment by pops64** [comment]
`[INFO]: >>> Removing orphan download: ******` Works

**Comment by ManiMatter** [comment]
Thx for testing and the code contribution, will merge now to latest

**Pull request merged**
