### PR TITLE
Arm support

### PR DESCRIPTION
**Pull request by craggles17**
Uses buildx to support arm aswell as x85

### CODE REVIEW

**Comment by Fxsch** [comment]
Just wanted to tell you that I forked this and merged your pull request because I needed ARM support. I also fixed the docker-compose.

**Comment by ManiMatter** [comment]
hi @craggles17  and @Fxsch 

I have merged your code (thank you for your contributions).
However, in the latest version I have commented out the "buildx" items again in the "dev.yml" and "main.yml", because when pulling the "dev" and "latest" images I got "Manifest Unknown" error.

I tried to solve it for many hours but I really have no clue how to solve it. 
If you have an idea, I'd highly appreciate another PR on to the dev branch, so we can test it there.

**Comment by craggles17** [comment]
I’ll have a look no worries

**Comment by ManiMatter** [comment]
hi @craggles17  - just wanted to check if you are able to use the latest version of decluttarr image (which does not have the arm compatibilty items you had added since I had encountered the "Manifest unknown" error). If not, still appreciate a PR to add compatibility so that you can again use it. cheers

**Comment by craggles17** [comment]
On my todo list. I finally have an arm machine now to test locally

**Pull request merged**
