### PR TITLE
Update remove_slow.py. Fixes #36

### LINKED ISSUE #36: Sonarr queue cleaning failed - List out of range
Hey, cool project!

Running into the following issue:

`Queue cleaning failed on Sonarr. (File: remove_slow.py / Line: 21 / Error Message: list index out of range / Error Type: <class 'IndexError'>)`

If you need any extra debug stuff feel free to ask :) I'm running with the latest version of the script (at the time of writing) with a standard docker-compose setup. Running develop version of Sonarr and latest of qBittorrent.

### PR DESCRIPTION
**Pull request by TheNetworkGuy**
Slow downloads check will only run with torrent type entries. Usenet entries will be skipped.

### CODE REVIEW

**Comment by TheNetworkGuy** [comment]
Just a quick thought: you could also fix this globally by implementing the check in the get_queue() function under shared.py. However i will leave it up to you on which level you would want to skip usenet based downloads.

**Comment by ManiMatter** [comment]
Thought:
Can this be instead changed?
From
 if settings_dict['QBITTORRENT_URL']:
 
To
 if settings_dict['QBITTORRENT_URL'] and queueitem[downloadClient]=qbittorrent

Then the slow check would still work for all doenload types but only torrents would be checked against qbit (snd only if thats the torrent client) else vs arr-queue status directly (which is less frequently updated)

**Comment by TheNetworkGuy** [comment]
Yes this seems to work as well! I'll modify my request.

[DEBUG]: getDownloadedSize/WARN: Using imprecise method to determine download increments because no direct qBIT query is possible

**Comment by TheNetworkGuy** [comment]
Just updated the code, validated on my own setup, moved the check to the getDownloadedSize() function and seems to work!

**Comment by ManiMatter** [comment]
hi, I changed the target branch to "dev", so we can build it there first. Above says there are conflicts, and I don't seem able to resolve it (guess cause the branch is in your git profile) -> can you please have a look? once resolved, will merge to dev and then you can pull & test

**Comment by TheNetworkGuy** [comment]
The conflict is because you previously placed the content of the function getDownloadedSize inside of a try / except block. I forked main which does not have this change. You can either approve the merge and get rid of the try / except block (like it is in main as well) or i can add the try / except block to my code.

My preference would be to go for the first option since we eventually want to merge this to main which does not have a try / except block (was placed there for troubleshooting.)

**Comment by TheNetworkGuy** [comment]
Seems good to me now. No idea why the return statement is acting funny but its the exact same.

**Comment by ManiMatter** [comment]
Mh. Do you want to simply quickly fork from dev; copy the new code snd create another pr back to dev snd close this one?

**Pull request closed without merging**
